//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonusMvcStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Musteriler
	{
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteriler()
        {
            this.Satislar = new HashSet<Satislar>();
        }
    
        public int Id { get; set; }

		[Required(ErrorMessage = "Ad Alanýný Boþ Geçemezsiniz...")]
        [StringLength(30,ErrorMessage ="Ad Alaný 30 Karakterden Büyük Olamaz...")]
		public string MusteriAd { get; set; }

		[Required(ErrorMessage = "Soyad Alanýný Boþ Geçemezsiniz...")]
		[StringLength(30, ErrorMessage = "Soyad Alaný 30 Karakterden Büyük Olamaz...")]
		public string MusteriSoyad { get; set; }
		public string MusteriSehir { get; set; }
        public Nullable<decimal> MusteriBakiye { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }
    }
}
